import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../app/components/Header"
import Footer from "../app/components/Footer"
import { Old_Standard_TT } from 'next/font/google';

const oldStandart = Old_Standard_TT({
    subsets: ['latin'], // Desteklenen karakter kümesi
    weight: ['400', '700'], // Kullanılacak font ağırlıkları
    style: ['normal', 'italic'], // Normal veya italik stiller
    display: 'swap', // Daha iyi yükleme için "swap" kullanılır
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={oldStandart.className}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
