import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppShell from "../app/components/AppShell";
import { Old_Standard_TT } from 'next/font/google';
import { Oswald } from "next/font/google";
import { Roboto } from "next/font/google";

const oldStandart = Old_Standard_TT({
    subsets: ['latin'], // Desteklenen karakter kümesi
    weight: ['400', '700'], // Kullanılacak font ağırlıkları
    style: ['normal', 'italic'], // Normal veya italik stiller
    display: 'swap', // Daha iyi yükleme için "swap" kullanılır
});

const oswald = Oswald({
  subsets: ['latin'], // Desteklenen karakter kümesi
  weight: ['400', '700'], // Kullanılacak font ağırlıkları
  style: ['normal'], // Normal veya italik stiller
  display: 'swap', // Daha iyi yükleme için "swap" kullanılır
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const roboto = Roboto({
  subsets: ['latin'], // Desteklenen karakter kümesi
  weight: ['100', '400', '500', '700'], // Kullanılacak font ağırlıkları
  style: ['normal'], // Normal veya italik stiller
  display: 'swap', // Daha iyi yükleme için "swap" kullanılır
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
